task_config: 'task_config/metaworld_ml1.json'
seed: 1
sampler: multi
snapshot_load: False
snapshot_path: ./outputs
outer_policy_lr: 1e-4
outer_value_lr: 1e-4
inner_policy_lr: 1e-2
inner_value_lr: 1e-2
inner_buffer_size: -1
outer_buffer_size: -1
weight_transform: True
include_goal: False
advantage_head_coef: 1e-3
net_width: 256
net_depth: 3
device: cpu
outer_batch_size: 256
inner_batch_size: 256
rollout_interval: 200
epoch_interval: 500
eval_batch_size: 256
render: False
discount: 0.99